Add a get options function. Don't call it yet
Signed-off-by: Joel Granados <joel.granados@joelgranados.com>

diff --git a/krc/krc b/krc/krc
--- a/krc/krc
+++ b/krc/krc
@@ -28,6 +28,51 @@ _usage() {
     exit 0
 }
 
+get_krc_opts()
+{
+  local short="x:h"
+  local long="cross-compile:help"
+
+  if ! tmp=$(getopt -o "$short" --long "$long" -n "$BASENAME" -- "$@"); then
+    exit 1
+  fi
+  eval set -- "$tmp"
+  unset tmp
+
+  while true; do
+    case "$1" in
+      '-x' | '--cross-compile' )
+        xcomp_arch=$2; shift 2
+        ;;
+
+      '-h' | '--help' )
+        _usage "${USAGE}" 0
+        ;;
+
+      '--' )
+        shift 1; break
+        ;;
+
+      * )
+        _usage "${USAGE}" 1
+        ;;
+
+    esac
+  done
+
+  shift $((OPTIND -1))
+  # Make sure args are: "$@ = HOST COMMAND"
+  if [ $# -lt 2 ]; then
+    echo "Error: You are missing an argument"
+    _usage "${USAGE}" 1
+  fi
+
+  HOST=$1; shift 1;
+
+  # Update args after filtering out [OPTIONS]
+  cmd_args="$@"
+}
+
 mutagen_sync()
 {
   local sess=$1
